config:
  clients:
    - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push

  snippets:
    pipelineStages:
      - cri: {}

extraScrapeConfigs: []
service:
  enabled: true
rbac:
  create: true
serviceAccount:
  create: true

# Labels Ãºtiles con cardinalidad controlada
configMap:
  enabled: true
